### ISSUE TITLE
adf4351 support

### ISSUE THREAD

**Issue by Sorush-moradisani** [JQIamo/ADF4350-arduino#2]
Hi. does it support adf4351? and is there any option to set vco output using divider?

**Comment by npisenti** [comment]
I think it should be compatible with the ADF4351, although I haven't tested this!

As for the VCO output divider, it is set automatically in `setFreq` (see [here](https://github.com/JQIamo/ADF4350-arduino/blob/master/ADF4350.cpp#L77)). If that's something you want access to manually, it'd be pretty straight forward to add a setter method for `_divider`, which writes to R4(DB22-DB20) during `update()`.

**Comment by npisenti** [comment]
(incidentally, there are a few features on the ADF4351 which aren't on the ADF4350, which won't work out of the box. Related to the output divider question, you'll need an edge case in `setFreq` for lower frequencies using the /64 capability on the ADF4351)

**Comment by Sorush-moradisani** [comment]
thanks a lot. can I have the wiring diagram too?

**Comment by npisenti** [comment]
I don't have a wiring diagram per se, but what you'll need to do is connect the SPI port to the corresponding pins on the ADF4351. eg:

Arduino | ADF4351
SCLK -> CLK
MOSI -> DATA
SS -> LE
GND -> DGND

Note, the slave select (SS) is software-emulated, so when you declare the ADF4350 object, pass whichever pin you want to use as a slave select. Also, you'll want to be sure to attach the grounds between the ADF4350 and arduino in whatever cable you're using to connect the SPI bus. I didn't do this at one point, and the parasitic inductance of the wire basically low-pass filtered all of my data/clock pulses and corrupted the datapacket as read by the ADF4350.

Hope that helps!
Neal

**Comment by Sorush-moradisani** [comment]
Thanks I really apreciate your advise! One last question! How can I put data on the generated frequency? Does it need to be connected to a reference crystal in port refin???

**Comment by npisenti** [comment]
Depends... If you're using one of the Eval boards, it should have an
onboard crystal oscillator in which case you don't have to supply a
reference frequency!

**Comment by Sorush-moradisani** [comment]
Thanks a lot! It was really helpful!
